
package com.mycuteblog.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibraryWebService", targetNamespace = "http://service.mycuteblog.com/", wsdlLocation = "file:/usr/local/jboss-5.1.0.GA/server/default/data/wsdl/sample-ear-1.0-SNAPSHOT.ear/web-service.jar/LibraryWebService1902846735230590610.wsdl")
public class LibraryWebService_Service
    extends Service
{

    private final static URL LIBRARYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBRARYWEBSERVICE_EXCEPTION;
    private final static QName LIBRARYWEBSERVICE_QNAME = new QName("http://service.mycuteblog.com/", "LibraryWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/usr/local/jboss-5.1.0.GA/server/default/data/wsdl/sample-ear-1.0-SNAPSHOT.ear/web-service.jar/LibraryWebService1902846735230590610.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRARYWEBSERVICE_WSDL_LOCATION = url;
        LIBRARYWEBSERVICE_EXCEPTION = e;
    }

    public LibraryWebService_Service() {
        super(__getWsdlLocation(), LIBRARYWEBSERVICE_QNAME);
    }

    public LibraryWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRARYWEBSERVICE_QNAME, features);
    }

    public LibraryWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, LIBRARYWEBSERVICE_QNAME);
    }

    public LibraryWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRARYWEBSERVICE_QNAME, features);
    }

    public LibraryWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LibraryWebService
     */
    @WebEndpoint(name = "LibraryWebServicePort")
    public LibraryWebService getLibraryWebServicePort() {
        return super.getPort(new QName("http://service.mycuteblog.com/", "LibraryWebServicePort"), LibraryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibraryWebService
     */
    @WebEndpoint(name = "LibraryWebServicePort")
    public LibraryWebService getLibraryWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.mycuteblog.com/", "LibraryWebServicePort"), LibraryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRARYWEBSERVICE_EXCEPTION!= null) {
            throw LIBRARYWEBSERVICE_EXCEPTION;
        }
        return LIBRARYWEBSERVICE_WSDL_LOCATION;
    }

}
