
package com.mycuteblog.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibraryWebService", targetNamespace = "http://service.mycuteblog.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.mycuteblog.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooks", targetNamespace = "http://service.mycuteblog.com/", className = "com.mycuteblog.service.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "http://service.mycuteblog.com/", className = "com.mycuteblog.service.GetBooksResponse")
    public List<Book> getBooks();

}
